name: Build

on: [push, pull_request]

jobs:
    GCC:
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: false
          matrix:
            cxxstd: [20, 23]

        steps:
        - uses: actions/checkout@v4

        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build gcc-12

        - name: Build
          run: >
            ./build.sh
            -DCMAKE_CXX_STANDARD=${{matrix.cxxstd}}
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_C_COMPILER=gcc-12
            -DCMAKE_CXX_COMPILER=g++-12
            -Dpapilio_build_unit_test=1
            -Dpapilio_build_example=1
            -Dpapilio_c_interface=1

        - name: Test
          working-directory: ${{github.workspace}}/build
          run: ctest

    # Temporarily disable clang build due to https://github.com/actions/runner-images/issues/8659
    # Clang:
    #     runs-on: ubuntu-22.04
    #     strategy:
    #       fail-fast: false
    #       matrix:
    #         compiler: [14, 15]
    #         cxxstd: [20]

    #     steps:
    #     - uses: actions/checkout@v4

    #     - name: Install Dependencies
    #       run: |
    #         sudo apt-get update
    #         sudo apt-get install -y cmake ninja-build clang-${{matrix.compiler}}

    #     - name: Build
    #       run: >
    #         ./build.sh
    #         -DCMAKE_CXX_STANDARD=${{matrix.cxxstd}}
    #         -DCMAKE_BUILD_TYPE=Release
    #         -DCMAKE_C_COMPILER=clang-${{matrix.compiler}}
    #         -DCMAKE_CXX_COMPILER=clang++-${{matrix.compiler}}
    #         -Dpapilio_build_unit_test=1
    #         -Dpapilio_build_example=1
    #         -Dpapilio_c_interface=1

    #     - name: Test
    #       working-directory: ${{github.workspace}}/build
    #       run: ctest

    MSVC:
      runs-on: windows-2022
      strategy:
        fail-fast: false
        matrix:
          cxxstd: [20, 23]

      env:
        VCPKG_BUILD_TYPE: release
        VCPKG_DEFAULT_TRIPLET: x64-windows

      steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Build
        run: >
          ./build.ps1
          -DCMAKE_CXX_STANDARD=${{matrix.cxxstd}}
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake"
          -Dpapilio_build_unit_test=1
          -Dpapilio_build_example=1
          -Dpapilio_c_interface=1

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest
