name: Build

on: [push, pull_request]

jobs:
    Linux:
        runs-on: ubuntu-22.04

        env:
            BUILD_TYPE: Release

        steps:
        - uses: actions/checkout@v4

        - name: Install Dependencies
          run: |
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build gcc-12 libgtest-dev

        - name: Build
          run: ./build.sh -DCMAKE_C_COMPILER=gcc-12 -DCMAKE_CXX_COMPILER=g++-12 -Dpapilio_build_unit_test=1 -Dpapilio_build_example=1

        - name: Test
          working-directory: ${{github.workspace}}/build
          run: ctest

    Windows:
      runs-on: windows-2022

      env:
        BUILD_TYPE: Release
        VCPKG_DEFAULT_TRIPLET: x64-windows

      steps:
      - uses: actions/checkout@v4
      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: amd64

      - name: Install Dependencies
        run: |
          C:\vcpkg\vcpkg.exe install gtest

      - name: Build
        run: ./build.ps1 -DCMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" -Dpapilio_build_unit_test=1 -Dpapilio_build_example=1

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest
